[env]
CFE_DIR = { value = "../../cfe/", relative = true }
OSAL_DIR = { value = "../../osal/", relative = true }
PSP_DIR = { value = "../../psp/", relative = true }
BUILD_DIR = { value = "../../build/", relative = true }
HWLIB_DIR = { value = "../../libs/nos3/fsw/apps/hwlib/", relative = true }
NOS3_COMPONENTS_DIR = { value = "../../libs/nos3/components/", relative = true }
