#ifndef DEFAULT_ROUTER_PLATFORM_CFG_H
#define DEFAULT_ROUTER_PLATFORM_CFG_H

#define ROUTER_NUM_ORBS  3
#define ROUTER_NUM_SATS  3

#define ROUTER_MAX_ROUTES    8

#define ROUTER_ROUTE_0_APID  0x70
#define ROUTER_ROUTE_0_TOPIC 0x96
#define ROUTER_ROUTE_1_APID  0x71
#define ROUTER_ROUTE_1_TOPIC 0x97
#define ROUTER_ROUTE_2_APID  0x60
#define ROUTER_ROUTE_2_TOPIC 0x98

#endif
