/*!
Low-level FFI bindings for NASA's 42 spacecraft dynamics simulator.

This module contains the raw, `unsafe` function and type definitions
generated by `rust-bindgen`. It is not intended for direct use by
applications — safe wrappers should be used instead.
*/

#![allow(clippy::all)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(overflowing_literals)]
#![allow(missing_docs)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
