#![cfg_attr(not(feature = "std"), no_std)]
#![deny(missing_docs)]

//! Safe Rust bindings for NASA's 42 spacecraft dynamics
//! simulator.

/// Raw FFI bindings generated by bindgen.
#[allow(missing_docs)]
pub mod ffi;

/// Direction cosine matrix, quaternion, and Euler angle
/// conversions.
pub mod dcm;
/// Environment models (gravity, atmosphere, magnetic field).
pub mod env;
/// Linear algebra, interpolation, and numerical utilities.
pub mod math;
/// Orbital mechanics (Keplerian elements, TLE, Lagrange
/// points, Lambert problem, Euler-Hill modes).
pub mod orbit;
/// Signal processing (random processes, filters, delays).
pub mod signal;
/// Simulation lifecycle, spacecraft types, and step
/// functions.
pub mod sim;
/// Time conversions (Julian date, GPS, calendar dates).
pub mod time;
/// Common array type aliases used throughout the crate.
pub mod types;
