[env]
CFE_DIR = { value = "../../cfe/", relative = true }
OSAL_DIR = { value = "../../osal/", relative = true }
PSP_DIR = { value = "../../psp/", relative = true  }
BUILD_DIR = { value = "../../build/", relative = true }
CF_DIR = { value = "../../libs/cf/", relative = true }
