[env]
CFE_DIR = { value = "../../cfe/", relative = true }
OSAL_DIR = { value = "../../osal/", relative = true }
PSP_DIR = { value = "../../psp/", relative = true  }
BUILD_DIR = { value = "../../build/", relative = true }
SYSROOT= { value = "/opt/homebrew/Cellar/aarch64-unknown-linux-gnu/13.3.0/toolchain/bin/../aarch64-unknown-linux-gnu/sysroot/" }

[build]
target = "aarch64-unknown-linux-gnu"
