//! Communications Link Control Word (CLCW).
//!
//! CCSDS 232.1-B-2, carried in the OCF of TM/AOS frames.
//! The CLCW is a 32-bit word generated by FARM-1 to report its
//! state back to FOP-1.
//!
//! ```text
//! Bit  0     : Control Word Type (0 = CLCW)
//! Bits 1-2   : CLCW Version Number
//! Bits 3-5   : Status Field
//! Bits 6-7   : COP in Effect (01 = COP-1)
//! Bits 8-13  : Virtual Channel Identifier
//! Bits 14-15 : Reserved Spare
//! Bit  16    : No RF Available Flag
//! Bit  17    : No Bit Lock Flag
//! Bit  18    : Lockout Flag
//! Bit  19    : Wait Flag
//! Bit  20    : Retransmit Flag
//! Bits 21-22 : FARM-B Counter (2 bits)
//! Bit  23    : Reserved Spare
//! Bits 24-31 : Report Value (N(R) = V(R))
//! ```

use zerocopy::FromBytes;
use zerocopy::Immutable;
use zerocopy::IntoBytes;
use zerocopy::KnownLayout;
use zerocopy::Unaligned;
use zerocopy::byteorder::network_endian::U32;

/// A 32-bit Communications Link Control Word.
#[repr(C)]
#[derive(
    FromBytes, IntoBytes, KnownLayout, Unaligned, Immutable,
    Debug, Copy, Clone, Eq, PartialEq,
)]
pub struct Clcw {
    word: U32,
}

#[rustfmt::skip]
mod bitmask {
    pub const TYPE_MASK:        u32 = 0b_1000_0000_0000_0000_0000_0000_0000_0000;
    pub const VERSION_MASK:     u32 = 0b_0110_0000_0000_0000_0000_0000_0000_0000;
    pub const STATUS_MASK:      u32 = 0b_0001_1100_0000_0000_0000_0000_0000_0000;
    pub const COP_MASK:         u32 = 0b_0000_0011_0000_0000_0000_0000_0000_0000;
    pub const VCID_MASK:        u32 = 0b_0000_0000_1111_1100_0000_0000_0000_0000;
    pub const NO_RF_MASK:       u32 = 0b_0000_0000_0000_0000_1000_0000_0000_0000;
    pub const NO_BIT_LOCK_MASK: u32 = 0b_0000_0000_0000_0000_0100_0000_0000_0000;
    pub const LOCKOUT_MASK:     u32 = 0b_0000_0000_0000_0000_0010_0000_0000_0000;
    pub const WAIT_MASK:        u32 = 0b_0000_0000_0000_0000_0001_0000_0000_0000;
    pub const RETRANSMIT_MASK:  u32 = 0b_0000_0000_0000_0000_0000_1000_0000_0000;
    pub const FARM_B_MASK:      u32 = 0b_0000_0000_0000_0000_0000_0110_0000_0000;
    pub const REPORT_MASK:      u32 = 0b_0000_0000_0000_0000_0000_0000_1111_1111;
}

use bitmask::*;

fn get(word: U32, mask: u32) -> u32 {
    (word.get() & mask) >> mask.trailing_zeros()
}

fn set(word: &mut U32, mask: u32, value: u32) {
    word.set((word.get() & !mask) | (value << mask.trailing_zeros()));
}

impl Clcw {
    /// Size of a CLCW in bytes.
    pub const SIZE: usize = 4;

    /// Create a new CLCW with all fields zeroed.
    pub fn new() -> Self {
        Self { word: U32::ZERO }
    }

    /// Parse a CLCW from a 4-byte slice.
    pub fn parse(bytes: &[u8]) -> Option<&Self> {
        Self::ref_from_bytes(bytes).ok()
    }

    /// Control Word Type (always 0 for CLCW).
    pub fn control_word_type(&self) -> u8 {
        get(self.word, TYPE_MASK) as u8
    }

    /// CLCW version number (should be 0).
    pub fn version(&self) -> u8 {
        get(self.word, VERSION_MASK) as u8
    }
    /// Sets the CLCW version.
    pub fn set_version(&mut self, v: u8) {
        set(&mut self.word, VERSION_MASK, v as u32);
    }

    /// Status field (3 bits, mission-specific).
    pub fn status(&self) -> u8 {
        get(self.word, STATUS_MASK) as u8
    }
    /// Sets the status field.
    pub fn set_status(&mut self, v: u8) {
        set(&mut self.word, STATUS_MASK, v as u32);
    }

    /// COP in effect (01 = COP-1).
    pub fn cop_in_effect(&self) -> u8 {
        get(self.word, COP_MASK) as u8
    }
    /// Sets the COP in effect field.
    pub fn set_cop_in_effect(&mut self, v: u8) {
        set(&mut self.word, COP_MASK, v as u32);
    }

    /// Virtual Channel Identifier (6 bits).
    pub fn vcid(&self) -> u8 {
        get(self.word, VCID_MASK) as u8
    }
    /// Sets the VCID.
    pub fn set_vcid(&mut self, v: u8) {
        set(&mut self.word, VCID_MASK, v as u32);
    }

    /// No RF Available flag.
    pub fn no_rf_available(&self) -> bool {
        get(self.word, NO_RF_MASK) != 0
    }
    /// Sets the No RF Available flag.
    pub fn set_no_rf_available(&mut self, v: bool) {
        set(&mut self.word, NO_RF_MASK, v as u32);
    }

    /// No Bit Lock flag.
    pub fn no_bit_lock(&self) -> bool {
        get(self.word, NO_BIT_LOCK_MASK) != 0
    }
    /// Sets the No Bit Lock flag.
    pub fn set_no_bit_lock(&mut self, v: bool) {
        set(&mut self.word, NO_BIT_LOCK_MASK, v as u32);
    }

    /// Lockout flag (FARM-1 is in Lockout state).
    pub fn lockout(&self) -> bool {
        get(self.word, LOCKOUT_MASK) != 0
    }
    /// Sets the Lockout flag.
    pub fn set_lockout(&mut self, v: bool) {
        set(&mut self.word, LOCKOUT_MASK, v as u32);
    }

    /// Wait flag (FARM-1 is in Wait state).
    pub fn wait(&self) -> bool {
        get(self.word, WAIT_MASK) != 0
    }
    /// Sets the Wait flag.
    pub fn set_wait(&mut self, v: bool) {
        set(&mut self.word, WAIT_MASK, v as u32);
    }

    /// Retransmit flag (a frame was lost or discarded).
    pub fn retransmit(&self) -> bool {
        get(self.word, RETRANSMIT_MASK) != 0
    }
    /// Sets the Retransmit flag.
    pub fn set_retransmit(&mut self, v: bool) {
        set(&mut self.word, RETRANSMIT_MASK, v as u32);
    }

    /// FARM-B counter (2-bit, incremented on BD/BC frames).
    pub fn farm_b_counter(&self) -> u8 {
        get(self.word, FARM_B_MASK) as u8
    }
    /// Sets the FARM-B counter.
    pub fn set_farm_b_counter(&mut self, v: u8) {
        set(&mut self.word, FARM_B_MASK, (v & 0x03) as u32);
    }

    /// Report value N(R) = V(R), the next expected frame sequence number.
    pub fn report_value(&self) -> u8 {
        get(self.word, REPORT_MASK) as u8
    }
    /// Sets the report value N(R).
    pub fn set_report_value(&mut self, v: u8) {
        set(&mut self.word, REPORT_MASK, v as u32);
    }
}

impl Default for Clcw {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip_fields() {
        let mut clcw = Clcw::new();

        clcw.set_cop_in_effect(1);
        clcw.set_vcid(42);
        clcw.set_lockout(true);
        clcw.set_wait(false);
        clcw.set_retransmit(true);
        clcw.set_farm_b_counter(3);
        clcw.set_report_value(0xAB);

        assert_eq!(clcw.control_word_type(), 0);
        assert_eq!(clcw.cop_in_effect(), 1);
        assert_eq!(clcw.vcid(), 42);
        assert!(clcw.lockout());
        assert!(!clcw.wait());
        assert!(clcw.retransmit());
        assert_eq!(clcw.farm_b_counter(), 3);
        assert_eq!(clcw.report_value(), 0xAB);
    }

    #[test]
    fn size_is_4_bytes() {
        assert_eq!(core::mem::size_of::<Clcw>(), 4);
    }

    #[test]
    fn parse_from_bytes() {
        let mut clcw = Clcw::new();
        clcw.set_report_value(99);
        let bytes = zerocopy::IntoBytes::as_bytes(&clcw);
        let parsed = Clcw::parse(bytes).unwrap();
        assert_eq!(parsed.report_value(), 99);
    }
}
