//! Defines the core data structures used to manage the state of a single CFDP transaction.
//!
//! A **transaction** is the complete, end-to-end activity of transferring a single file.
//! This module provides the `Transaction` struct, which holds all the state associated
//! with one such transfer, and the supporting types like `TransactionId` and `TransactionState`.
//!
//! The state machines (`SenderMachine` and `ReceiverMachine`) each maintain a map of these
//! `Transaction` objects to manage multiple concurrent file transfers.

use crate::cfdp::machine::tracker::SegmentTracker;
use crate::cfdp::pdu::{EntityId, TransactionSeqNum};
use heapless::Vec;

/// A unique identifier for a single CFDP transaction.
///
/// It is composed of the source entity's ID and a sequence number that is unique
/// for that source. This pair uniquely identifies a file transfer across the entire
/// CFDP network, allowing all related PDUs to be correlated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct TransactionId {
    /// The `EntityId` of the CFDP entity that initiated the transaction.
    pub source_entity_id: EntityId,
    /// A sequence number generated by the source entity, which is incremented for each new transaction.
    pub sequence_number: TransactionSeqNum,
}

/// The lifecycle state of a single transaction.
///
/// This enum tracks the progress of a file transfer from start to finish, for both
/// the sending and receiving entities.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TransactionState {
    // --- Source (Sender) States ---
    /// The sender is actively sending `FileData` PDUs.
    SendingFileData,
    /// The sender has sent the last `FileData` PDU and has now sent an `EOF` PDU.
    SendingEof,
    /// The sender is waiting for an `ACK` PDU in response to its `EOF` PDU.
    WaitingForEofAck,
    /// The sender has received the `EOF` acknowledgment and has sent a `Finished` PDU.
    /// It is now waiting for the final `ACK` for the `Finished` PDU.
    WaitingForFinishedAck,

    // --- Destination (Receiver) States ---
    /// The receiver is actively receiving `FileData` PDUs.
    ReceivingFileData,
    /// The receiver has received an `EOF` PDU, found the file to be complete, and has
    /// sent back an `ACK` PDU for the `EOF`.
    SendingEofAck,
    /// The receiver has received an `EOF` PDU, found data segments to be missing, and has
    /// sent a `NAK` PDU to request retransmission.
    SendingNak,

    // --- Common States ---
    /// The transaction has successfully completed. This is a terminal state.
    Complete,
    /// The transaction has been terminated due to an error condition. The contained value
    /// is the `ConditionCode` representing the fault. This is a terminal state.
    Faulted(u8),
}

/// The static configuration for a single transaction.
///
/// This struct holds all the information about a file transfer that does not change
/// during its lifetime, such as filenames and entity IDs.
#[derive(Debug, Clone)]
pub struct TransactionConfig {
    /// The unique identifier for this transaction.
    pub id: TransactionId,
    /// The EntityId of the destination for this transaction.
    pub dest_entity_id: EntityId,
    /// The name of the file at the source entity.
    pub source_file_name: Vec<u8, 256>,
    /// The name the file should have at the destination entity.
    pub destination_file_name: Vec<u8, 256>,
    /// The total size of the file in bytes.
    pub file_size: u64,
    /// The number of times to retry sending an expected ACK before faulting.
    pub ack_limit: u8,
    /// The number of times to retry sending a NAK sequence before faulting.
    pub nak_limit: u8,
    /// Timeout in seconds to wait for missing data after sending a NAK.
    pub nak_timeout_secs: u64,
    /// Timeout in seconds to wait for any PDU before declaring the transaction inactive.
    pub inactivity_timeout_secs: u64,
}

/// Holds all the dynamic state associated with a single, ongoing file transfer.
///
/// An instance of this struct represents one "active session" in the state machine.
#[derive(Debug, Clone)]
pub struct Transaction {
    /// The static configuration for this transaction.
    pub config: TransactionConfig,
    /// The current position in the transaction's lifecycle (e.g., `SendingFileData`).
    pub state: TransactionState,
    /// The number of bytes of the file that have been successfully sent or received.
    pub progress: u64,
    /// An optional data structure used by the receiver to track missing file segments.
    pub tracker: Option<SegmentTracker>,
    /// A counter for the number of times an expected `ACK` PDU has been retransmitted.
    pub ack_retries: u8,
    /// A counter for the number of times a `NAK` sequence has been retransmitted.
    pub nak_retries: u8,
}
