#![no_std]

use core::fmt::Write;
use leodos_libcfs::cfe::sb::pipe::Timeout;
use leodos_spacepacket::cfe::tc::Telecommand;
use leodos_spacepacket::cfe::tm::Telemetry;
use leodos_spacepacket::Apid;
use leodos_spacepacket::PacketSequenceCount;
use leodos_spacepacket::SpacePacket;
use zerocopy::FromBytes;
use zerocopy::Immutable;
use zerocopy::IntoBytes;
use zerocopy::KnownLayout;
use zerocopy::Unaligned;

use leodos_libcfs::cfe::es::app::AppMain;
use leodos_libcfs::cfe::es::perf::PerfMarker;
use leodos_libcfs::cfe::evs::event;
use leodos_libcfs::cfe::sb::msg::MessageRef;
use leodos_libcfs::cfe::sb::msg::MsgId;
use leodos_libcfs::cfe::sb::pipe::Pipe;
use leodos_libcfs::cfe::sb::send_buf::SendBuffer;
use leodos_libcfs::error::Result;
use leodos_libcfs::main; // The main! macro

// Include the bindings generated by `build.rs`.
// This gives us access to RUST_CMD_MID, RUST_HK_TLM_MID, etc.
mod bindings {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    include!(concat!(env!("OUT_DIR"), "/config.rs"));

    // For a real application, this would also be generated by the build system
    // from the mission definition. We define it here for the example.
    pub const RUST_HK_TLM_APID: u16 = 0x081;
}

const RUST_APP_INIT_EID: u16 = 1;
const RUST_APP_CMD_EID: u16 = 2;
const RUST_APP_CMD_ERR_EID: u16 = 3;
const RUST_APP_PIPE_ERR_EID: u16 = 4;
const RUST_APP_CMD_CSUM_ERR_EID: u16 = 5; // New event for checksum errors

const NOOP_CC: u8 = 0;
const RESET_COUNTERS_CC: u8 = 1;

/// Housekeeping telemetry packet structure.
/// It must derive the traits required by `leodos_spacepacket::SpacePacketData`.
#[repr(C)]
#[derive(Debug, Clone, Copy, IntoBytes, FromBytes, KnownLayout, Unaligned, Immutable)]
struct HkTelemetry {
    // The cFE Tlm Header is not part of this struct.
    // leodos-spacepacket handles adding it when sending the message.
    command_count: u8,
    command_error_count: u8,
    padding: [u8; 2], // for alignment
}

/// A generic command with no arguments.
/// The command function code is in the secondary header.
#[repr(C)]
#[derive(Debug, Clone, Copy, IntoBytes, FromBytes, KnownLayout, Unaligned, Immutable)]
struct NoArgsCmd {
    // cFE Cmd Header is handled by leodos-spacepacket
    // The payload is empty for these commands.
}

struct DemoApp {
    pipe: Pipe,
    command_count: u8,
    command_error_count: u8,
    tlm_sequence_count: PacketSequenceCount,
}

impl AppMain for DemoApp {
    /// Application initialization routine.
    fn init() -> Result<Self> {
        event::register(&[])?;

        // Create a software bus pipe.
        let pipe = Pipe::new("RUST_CMD_PIPE", 16)?;

        // Subscribe to command and housekeeping messages.
        pipe.subscribe(MsgId::from_global_cmd(bindings::RUST_CMD_MID as u16))?;
        pipe.subscribe(MsgId::from_global_cmd(bindings::RUST_SEND_HK_MID as u16))?;

        // Send an initialization event.
        event::info(RUST_APP_INIT_EID, "Rust App initialized.")?;

        Ok(Self {
            pipe,
            command_count: 0,
            command_error_count: 0,
            tlm_sequence_count: PacketSequenceCount::new(),
        })
    }

    /// Application main processing loop.
    fn run_cycle(&mut self) -> Result<()> {
        let _perf = PerfMarker::new(bindings::RUST_APPMAIN_PERF_ID as u32);

        // Process all messages on the pipe, with a non-blocking poll.
        // CFE messages have a max size. We allocate a buffer large enough for most.
        let mut msg_buffer = [0u8; 128];
        while let Ok(msg) = self.pipe.receive(Timeout::Poll, &mut msg_buffer) {
            self.process_message(msg)?;
        }

        Ok(())
    }
}

impl DemoApp {
    /// Processes a single message received from the software bus pipe.
    fn process_message(&mut self, msg: MessageRef) -> Result<()> {
        let msg_id = msg.msg_id()?;

        // Use the CFE-specific MsgId for routing, as it contains more than just the APID.
        if msg_id == MsgId::from_global_cmd(bindings::RUST_CMD_MID as u16) {
            // Parse the generic message slice into a typed SpacePacket view
            let sp = SpacePacket::parse(msg.as_slice()).unwrap();
            self.process_command(sp)?;
        } else if msg_id == MsgId::from_global_cmd(bindings::RUST_SEND_HK_MID as u16) {
            self.report_housekeeping()?;
        } else {
            let mut message = heapless::String::<128>::new();
            write!(message, "Got unexpected MID: {:#04x}", msg_id.value()).ok();
            event::error(RUST_APP_PIPE_ERR_EID, &message)?;
        }
        Ok(())
    }

    /// Dispatches ground commands based on function code.
    fn process_command(&mut self, sp: &SpacePacket) -> Result<()> {
        // Try to interpret the SpacePacket as a CFE Telecommand with our expected payload type.
        let cmd = match <&Telecommand<NoArgsCmd>>::try_from(sp) {
            Ok(c) => c,
            Err(_) => {
                self.command_error_count = self.command_error_count.saturating_add(1);
                event::error(RUST_APP_CMD_ERR_EID, "Failed to parse command packet.")?;
                return Ok(());
            }
        };

        // Validate the checksum before processing the command.
        if !cmd.validate_cfe_checksum() {
            self.command_error_count = self.command_error_count.saturating_add(1);
            event::error(RUST_APP_CMD_CSUM_ERR_EID, "Checksum validation failed.")?;
            return Ok(());
        }

        // Access the function code directly from the typed secondary header.
        match cmd.secondary.function_code {
            NOOP_CC => {
                self.command_count = self.command_count.saturating_add(1);
                event::info(RUST_APP_CMD_EID, "No-op command received.")?;
            }
            RESET_COUNTERS_CC => {
                self.command_count = 0;
                self.command_error_count = 0;
                event::debug(RUST_APP_CMD_EID, "Reset counters command received.")?;
            }
            other => {
                self.command_error_count = self.command_error_count.saturating_add(1);
                let mut message = heapless::String::<64>::new();
                write!(message, "Invalid command code: {}", other).ok();
                event::error(RUST_APP_CMD_ERR_EID, &message)?;
            }
        }
        Ok(())
    }

    /// Populates and sends the housekeeping telemetry packet.
    fn report_housekeeping(&mut self) -> Result<()> {
        self.tlm_sequence_count.increment();

        let hk_payload = HkTelemetry {
            command_count: self.command_count,
            command_error_count: self.command_error_count,
            padding: [0, 0],
        };

        let mut send_buffer = SendBuffer::new(core::mem::size_of::<Telemetry<HkTelemetry>>())?;

        Telemetry::builder()
            .apid(Apid::new(bindings::RUST_HK_TLM_APID).unwrap())
            .sequence_count(self.tlm_sequence_count)
            .payload(&hk_payload)
            .buffer(send_buffer.as_mut_slice())
            .build()
            .expect("should fit in allocated send buffer");

        send_buffer.send(false)?;

        Ok(())
    }
}

// Define the application entry point, linking it to our `DemoApp` struct.
main!(DemoApp);

// Provide a panic handler that logs to the cFE System Log.
#[cfg(not(test))]
#[panic_handler]
fn panic(info: &core::panic::PanicInfo) -> ! {
    leodos_libcfs::cfe::es::app::default_panic_handler(info)
}
