#ifndef DEFAULT_SPACECOMP_WILDFIRE_PLATFORM_CFG_H
#define DEFAULT_SPACECOMP_WILDFIRE_PLATFORM_CFG_H

#define SPACECOMP_WILDFIRE_NUM_ORBITS  3
#define SPACECOMP_WILDFIRE_NUM_SATS    3
#define SPACECOMP_WILDFIRE_APID        0x61

#endif
